GET http://localhost:3000/schedule/init

###

POST http://localhost:3000/schedule/add
Content-Type: application/json

{
    "title": "Event",
    "color": "blue",
    "start": 1647961774139,
    "end": 1647961774139
}

### 

POST http://localhost:3000/schedule/edit
Content-Type: application/json

{
    "id": "6239e7ccadef34de93c6b94e",
    "title": "Event",
    "color": "red",
}